### ISSUE TITLE
Revision numbers should be respected, not ignored.

### ISSUE THREAD

**Issue by ferrouswheel** [norbu09/Store-CouchDB#4]
~~put_doc and~~ update_doc functions nuke a documents `_rev` key "for convenience".

EDIT: I checked again and put_doc doesn't do this, only update_doc does.

`_rev` specifically exists to avoid race conditions, but our update doc just reads whatever the current revno is in the db, and then assigns that to the document we are writing.

This breaks all expectations of consistency in our data... so we should really stop this and return an error when couch gives a "409 conflict error".

If a caller specifically wants to nuke the previous version, even if another process has modified it, then it should require a `force` attribute.

This also makes things slower because every write to the db requires an extra read.

**Comment by nupfel** [comment]
we actually don't use `update_doc` anywhere in our relevant code base, but i agree with the suggested behaviour change, however we won't be able to save on the extra read because that wasn't just for the
revision lookup but more for the existence check. `udpate_doc` was meant to never create new documents by accident, but fixed your suggestion and let it throw an error if the revision is missing or the updated caused a conflict error. see #10

**Comment by nupfel** [comment]
let me know if what i just deployed solves this issue in your opinion and feel free to comment or close it

**Comment by ferrouswheel** [comment]
Looks good - thanks!
